/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 进程、数据库与版本状态（不调用模型）
         * @description 独立响应体；不返回任意磁盘路径，也不触发任何模型调用。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入 TXT/EPUB（202 + IMPORT 任务） */
        post: operations["import_book_api_books_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 书籍列表 */
        get: operations["list_books_route_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 书籍详情 */
        get: operations["get_book_route_api_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目录（按 ordinal，EPUB 为 spine 顺序） */
        get: operations["list_chapters_route_api_books__book_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 结构化正文节点（章节或码点范围） */
        get: operations["content_route_api_books__book_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 受控资源（图片等，独立响应体） */
        get: operations["get_resource_route_api_books__book_id__resources__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/reading-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 保存阅读位置与阅读模式（不调用模型）
         * @description 保存书签：只写数据库，不触发任何模型调用。
         */
        put: operations["save_reading_progress_route_api_books__book_id__reading_progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务状态 */
        get: operations["get_job_route_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 候选引语列表（不含说话人判断） */
        get: operations["list_quotes_route_api_books__book_id__quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gap（相邻外层候选之间的叙述） */
        get: operations["list_gaps_route_api_books__book_id__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按码点范围定位原文（章节/节点/源文档） */
        get: operations["locate_route_api_books__book_id__locate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/quotes/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新扫描候选引语与 Gap（有用户标注时拒绝） */
        post: operations["scan_quotes_route_api_books__book_id__quotes_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 候选对白详情（含上下文与前置 Gap） */
        get: operations["get_quote_route_api_quotes__quote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_book_api_books_import_post */
        Body_import_book_api_books_import_post: {
            /**
             * File
             * @description TXT 或 EPUB 文件
             */
            file: string;
            /**
             * Encoding
             * @description 显式编码；留空自动检测（仅 TXT）
             */
            encoding?: string | null;
            /**
             * Title
             * @description 书名；留空用文件内元数据或文件名
             */
            title?: string | null;
        };
        /**
         * BookFormat
         * @enum {string}
         */
        BookFormat: "TXT" | "EPUB";
        /** BookOut */
        BookOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            format: components["schemas"]["BookFormat"];
            /** Source Sha256 */
            source_sha256: string;
            import_status: components["schemas"]["ImportStatus"];
            /** Read Position Cp */
            read_position_cp: number;
            /** @default initial */
            reading_mode: components["schemas"]["ReadingMode"];
            /** Version */
            version: number;
            /** Active Version Id */
            active_version_id?: string | null;
            active_version?: components["schemas"]["BookVersionOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BookVersionOut */
        BookVersionOut: {
            /** Id */
            id: string;
            /** Encoding */
            encoding: string;
            /** Parser Version */
            parser_version: string;
            /** Normalization Version */
            normalization_version: string;
            /** Canonical Sha256 */
            canonical_sha256: string;
            /** Canonical Length Cp */
            canonical_length_cp: number;
            /** Warnings */
            warnings?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChapterOut */
        ChapterOut: {
            /** Id */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Title */
            title?: string | null;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /** Source Href */
            source_href?: string | null;
        };
        /** ContentNodeOut */
        ContentNodeOut: {
            /** Node Id */
            node_id: string;
            node_type: components["schemas"]["ContentNodeType"];
            /** Ordinal */
            ordinal: number;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /** Chapter Id */
            chapter_id?: string | null;
            /** Chapter Ordinal */
            chapter_ordinal?: number | null;
            /** Text */
            text: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ContentNodeType
         * @description 统一文档树的受限节点类型（DEVELOPMENT.md 4.1）。
         *
         *     ruby/rb/rt/rp 单独保留，注音不重复进入模型正文。
         * @enum {string}
         */
        ContentNodeType: "paragraph" | "heading" | "image" | "ruby" | "rb" | "rt" | "rp" | "footnote" | "separator" | "other";
        /** ContentResponse */
        ContentResponse: {
            /** Book Id */
            book_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Canonical Length Cp */
            canonical_length_cp: number;
            /** Chapter Id */
            chapter_id?: string | null;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /** Nodes */
            nodes: components["schemas"]["ContentNodeOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CursorPage[BookOut] */
        CursorPage_BookOut_: {
            /** Items */
            items: components["schemas"]["BookOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CursorPage[GapOut] */
        CursorPage_GapOut_: {
            /** Items */
            items: components["schemas"]["GapOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CursorPage[QuoteOut] */
        CursorPage_QuoteOut_: {
            /** Items */
            items: components["schemas"]["QuoteOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DataEnvelope[BookOut] */
        DataEnvelope_BookOut_: {
            data: components["schemas"]["BookOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[ContentResponse] */
        DataEnvelope_ContentResponse_: {
            data: components["schemas"]["ContentResponse"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[CursorPage[BookOut]] */
        DataEnvelope_CursorPage_BookOut__: {
            data: components["schemas"]["CursorPage_BookOut_"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[CursorPage[GapOut]] */
        DataEnvelope_CursorPage_GapOut__: {
            data: components["schemas"]["CursorPage_GapOut_"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[CursorPage[QuoteOut]] */
        DataEnvelope_CursorPage_QuoteOut__: {
            data: components["schemas"]["CursorPage_QuoteOut_"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[ImportResult] */
        DataEnvelope_ImportResult_: {
            data: components["schemas"]["ImportResult"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[JobOut] */
        DataEnvelope_JobOut_: {
            data: components["schemas"]["JobOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[LocateOut] */
        DataEnvelope_LocateOut_: {
            data: components["schemas"]["LocateOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[QuoteDetailOut] */
        DataEnvelope_QuoteDetailOut_: {
            data: components["schemas"]["QuoteDetailOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[ReadingProgressOut] */
        DataEnvelope_ReadingProgressOut_: {
            data: components["schemas"]["ReadingProgressOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[ScanResultOut] */
        DataEnvelope_ScanResultOut_: {
            data: components["schemas"]["ScanResultOut"];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** DataEnvelope[list[ChapterOut]] */
        DataEnvelope_list_ChapterOut__: {
            /** Data */
            data: components["schemas"]["ChapterOut"][];
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /**
         * GapDecision
         * @enum {string}
         */
        GapDecision: "CONTINUE" | "UPDATE" | "BREAK" | "UNCERTAIN";
        /** GapOut */
        GapOut: {
            /** Gap Id */
            gap_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Left Quote Id */
            left_quote_id?: string | null;
            /** Right Quote Id */
            right_quote_id?: string | null;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /** Narration */
            narration: string;
            /** Paragraph Count */
            paragraph_count: number;
            decision: components["schemas"]["GapDecision"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Book Id */
            book_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Job Id */
            job_id: string;
            format: components["schemas"]["BookFormat"];
            import_status: components["schemas"]["ImportStatus"];
            /** Encoding */
            encoding?: string | null;
            /** Encoding Confidence */
            encoding_confidence?: string | null;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /**
             * Resource Count
             * @default 0
             */
            resource_count: number;
            /** Canonical Length Cp */
            canonical_length_cp: number;
            /** Reused Book */
            reused_book: boolean;
            /** Reused Version */
            reused_version: boolean;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ImportStatus
         * @description 导入状态与推理状态分离。
         * @enum {string}
         */
        ImportStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "IMPORT" | "INFERENCE" | "RECHECK" | "RECOMPUTE" | "EXPORT";
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            kind: components["schemas"]["JobKind"];
            purpose?: components["schemas"]["JobPurpose"] | null;
            state: components["schemas"]["JobState"];
            /** Book Id */
            book_id?: string | null;
            /** Book Version Id */
            book_version_id?: string | null;
            /** Progress */
            progress?: {
                [key: string]: unknown;
            } | null;
            /** Checkpoint */
            checkpoint?: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobPurpose
         * @description INFERENCE 的目的；preview/process 共用同一识别引擎与缓存。
         * @enum {string}
         */
        JobPurpose: "preview" | "process" | "none";
        /**
         * JobState
         * @enum {string}
         */
        JobState: "QUEUED" | "RUNNING" | "PAUSING" | "PAUSED" | "PARTIAL" | "COMPLETED" | "FAILED" | "BUDGET_EXHAUSTED" | "NEEDS_RECONCILIATION";
        /** LocateOut */
        LocateOut: {
            /** Book Id */
            book_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /** Text */
            text: string;
            /** Spans */
            spans: components["schemas"]["LocateSpanOut"][];
        };
        /** LocateSpanOut */
        LocateSpanOut: {
            /** Mapping Ordinal */
            mapping_ordinal: number;
            /** Chapter Id */
            chapter_id?: string | null;
            /** Chapter Ordinal */
            chapter_ordinal?: number | null;
            /** Node Id */
            node_id?: string | null;
            node_type?: components["schemas"]["ContentNodeType"] | null;
            /** Canonical Start Cp */
            canonical_start_cp: number;
            /** Canonical End Cp */
            canonical_end_cp: number;
            /** Source Href */
            source_href?: string | null;
            /** Source Text Start Cp */
            source_text_start_cp: number;
            /** Source Text End Cp */
            source_text_end_cp: number;
            /** Synthetic */
            synthetic: boolean;
            /** Text */
            text: string;
        };
        /** QuoteDetailOut */
        QuoteDetailOut: {
            quote: components["schemas"]["QuoteOut"];
            /** Previous Quote Id */
            previous_quote_id?: string | null;
            /** Next Quote Id */
            next_quote_id?: string | null;
            gap_before?: components["schemas"]["GapOut"] | null;
            /**
             * Context Before
             * @default
             */
            context_before: string;
            /**
             * Context After
             * @default
             */
            context_after: string;
        };
        /**
         * QuoteKind
         * @enum {string}
         */
        QuoteKind: "speech" | "thought" | "quotation" | "group" | "other" | "unknown";
        /** QuoteOut */
        QuoteOut: {
            /** Quote Id */
            quote_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Chapter Id */
            chapter_id?: string | null;
            /** Chapter Ordinal */
            chapter_ordinal?: number | null;
            /** Start Cp */
            start_cp: number;
            /** End Cp */
            end_cp: number;
            /**
             * Text
             * @description 引号内的文字（不含引号本身）。
             */
            text: string;
            /**
             * Delimited Text
             * @description 包含引号的原文片段。
             */
            delimited_text: string;
            /** Delimiter */
            delimiter: string;
            /** Opening */
            opening: string;
            /** Closing */
            closing: string;
            /** Nesting Depth */
            nesting_depth: number;
            /** Parent Quote Id */
            parent_quote_id?: string | null;
            kind_hint?: components["schemas"]["QuoteKind"] | null;
            /** Scanner Version */
            scanner_version: string;
        };
        /**
         * ReadingMode
         * @enum {string}
         */
        ReadingMode: "initial" | "reread";
        /**
         * ReadingProgressIn
         * @description 保存阅读书签：不调用模型，只写位置与模式。
         */
        ReadingProgressIn: {
            /** Book Version Id */
            book_version_id: string;
            /** Read Position Cp */
            read_position_cp: number;
            /** @default initial */
            reading_mode: components["schemas"]["ReadingMode"];
            /** Expected Version */
            expected_version?: number | null;
        };
        /** ReadingProgressOut */
        ReadingProgressOut: {
            /** Book Id */
            book_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Read Position Cp */
            read_position_cp: number;
            reading_mode: components["schemas"]["ReadingMode"];
            /** Version */
            version: number;
        };
        /** ScanResultOut */
        ScanResultOut: {
            /** Book Id */
            book_id: string;
            /** Book Version Id */
            book_version_id: string;
            /** Job Id */
            job_id: string;
            /** Scanner Version */
            scanner_version: string;
            /** Quote Count */
            quote_count: number;
            /** Top Level Quote Count */
            top_level_quote_count: number;
            /** Gap Count */
            gap_count: number;
            /** Warnings */
            warnings?: components["schemas"]["ScanWarningOut"][];
            /** Stats */
            stats?: {
                [key: string]: number;
            };
        };
        /** ScanWarningOut */
        ScanWarningOut: {
            /** Code */
            code: string;
            /** Position Cp */
            position_cp: number;
            /** Delimiter */
            delimiter: string;
            /** Detail */
            detail: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** DataEnvelope */
        DataEnvelope: {
            /** Data */
            data: unknown;
            /**
             * Request Id
             * @description 本次请求的追踪 ID，与响应头 X-Request-ID 一致。
             */
            request_id: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description 稳定业务错误码，见 domain.enums.ErrorCode。
             */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
            /** Request Id */
            request_id: string;
        };
        /** CursorPage */
        CursorPage: {
            /** Items */
            items: unknown[];
            /**
             * Next Cursor
             * @default null
             */
            next_cursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    import_book_api_books_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_book_api_books_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_books_route_api_books_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_CursorPage_BookOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_route_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_BookOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_route_api_books__book_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_ChapterOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_route_api_books__book_id__content_get: {
        parameters: {
            query?: {
                chapter_id?: string | null;
                start_cp?: number | null;
                end_cp?: number | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ContentResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_route_api_books__book_id__resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_reading_progress_route_api_books__book_id__reading_progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingProgressIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ReadingProgressOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_route_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_JobOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quotes_route_api_books__book_id__quotes_get: {
        parameters: {
            query?: {
                chapter_id?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_CursorPage_QuoteOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gaps_route_api_books__book_id__gaps_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_CursorPage_GapOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_route_api_books__book_id__locate_get: {
        parameters: {
            query: {
                start_cp: number;
                end_cp: number;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_LocateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_quotes_route_api_books__book_id__quotes_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ScanResultOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_route_api_quotes__quote_id__get: {
        parameters: {
            query?: {
                context_window_cp?: number;
            };
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_QuoteDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
