"""领域枚举与 API schema 包。

后端是枚举与 schema 的权威定义（DEVELOPMENT.md 3.1）；前端类型由 OpenAPI 生成，
不维护第二份会漂移的枚举。
"""

from __future__ import annotations

from .common import (
    ApiModel,
    CursorPage,
    DataEnvelope,
    ErrorBody,
    ErrorEnvelope,
)
from .documents import (
    BookOut,
    BookVersionOut,
    ChapterOut,
    ContentNodeOut,
    ContentResponse,
    ImportResult,
    JobOut,
)
from .enums import (
    AnnotationSource,
    AnnotationStatus,
    Assignment,
    BookFormat,
    ContentNodeType,
    CorrectionAction,
    CorrectionTargetType,
    CredentialMode,
    DatabaseState,
    ErrorCode,
    ExportFormat,
    ExportStylePreset,
    GapDecision,
    IdentityOperation,
    ImportStatus,
    InferenceRunState,
    JobKind,
    JobPurpose,
    JobState,
    QuoteKind,
    ReadingMode,
    ReviewQueueStatus,
    ReviewReason,
    ReviewTargetType,
    SceneStatus,
    SpeakerBasis,
    VisibilityPolicy,
)
from .profiles import (
    ModelProfileCreate,
    ModelProfileOut,
    ModelProfilePatch,
    ProtocolCapabilitiesOut,
)

__all__ = [
    "AnnotationSource",
    "AnnotationStatus",
    "ApiModel",
    "Assignment",
    "BookFormat",
    "BookOut",
    "BookVersionOut",
    "ChapterOut",
    "ContentNodeOut",
    "ContentNodeType",
    "ContentResponse",
    "CorrectionAction",
    "CorrectionTargetType",
    "CredentialMode",
    "CursorPage",
    "DataEnvelope",
    "DatabaseState",
    "ErrorBody",
    "ErrorCode",
    "ErrorEnvelope",
    "ExportFormat",
    "ExportStylePreset",
    "GapDecision",
    "IdentityOperation",
    "ImportResult",
    "ImportStatus",
    "InferenceRunState",
    "JobKind",
    "JobOut",
    "ModelProfileCreate",
    "ModelProfileOut",
    "ModelProfilePatch",
    "ProtocolCapabilitiesOut",
    "JobPurpose",
    "JobState",
    "QuoteKind",
    "ReadingMode",
    "ReviewQueueStatus",
    "ReviewReason",
    "ReviewTargetType",
    "SceneStatus",
    "SpeakerBasis",
    "VisibilityPolicy",
]
