"""0001 核心表：书籍/版本、文档、引语、场景、标注、模型配置与任务

Revision ID: 0001
Revises: (无，初始迁移)
Create Date: 2026-09-28 01:03:38.556576

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ndr.storage.types  # noqa: F401 - UtcDateTime 列类型需要模块可见


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('TXT', 'EPUB', name='book_format', native_enum=False), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('import_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='import_status', native_enum=False), nullable=False),
    sa.Column('read_position_cp', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_active_version_id'), ['active_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_source_sha256'), ['source_sha256'], unique=False)

    op.create_table('model_profiles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('credential_mode', sa.Enum('session', 'system', 'none', name='credential_mode', native_enum=False), nullable=False),
    sa.Column('credential_ref', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_profiles')),
    sa.UniqueConstraint('name', name='uq_model_profiles_name')
    )
    op.create_table('result_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('dependency_hash', sa.String(length=64), nullable=True),
    sa.Column('created_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_cache')),
    sa.UniqueConstraint('cache_key', name='uq_result_cache_cache_key')
    )
    op.create_table('book_versions',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('encoding', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('normalization_version', sa.String(length=64), nullable=False),
    sa.Column('canonical_sha256', sa.String(length=64), nullable=False),
    sa.Column('canonical_length_cp', sa.Integer(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_versions_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_versions')),
    sa.UniqueConstraint('book_id', 'canonical_sha256', 'parser_version', 'normalization_version', name='uq_book_versions_identity')
    )
    with op.batch_alter_table('book_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_versions_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_versions_canonical_sha256'), ['canonical_sha256'], unique=False)

    op.create_table('chapters',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('start_cp', sa.Integer(), nullable=False),
    sa.Column('end_cp', sa.Integer(), nullable=False),
    sa.Column('source_href', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_chapters_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('book_version_id', 'ordinal', name='uq_chapters_book_version_id_ordinal')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_book_version_id'), ['book_version_id'], unique=False)

    op.create_table('jobs',
    sa.Column('kind', sa.Enum('IMPORT', 'INFERENCE', 'RECHECK', 'RECOMPUTE', 'EXPORT', name='job_kind', native_enum=False), nullable=False),
    sa.Column('purpose', sa.Enum('preview', 'process', 'none', name='job_purpose', native_enum=False), nullable=True),
    sa.Column('book_id', sa.String(length=36), nullable=True),
    sa.Column('book_version_id', sa.String(length=36), nullable=True),
    sa.Column('range_json', sa.Text(), nullable=False),
    sa.Column('profile_snapshot_json', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'PAUSING', 'PAUSED', 'PARTIAL', 'COMPLETED', 'FAILED', 'BUDGET_EXHAUSTED', 'NEEDS_RECONCILIATION', name='job_state', native_enum=False), nullable=False),
    sa.Column('budget_json', sa.Text(), nullable=False),
    sa.Column('checkpoint_json', sa.Text(), nullable=True),
    sa.Column('progress_json', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_digest', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_jobs_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_jobs_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_book_version_id'), ['book_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)

    op.create_table('resources',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_resources_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('book_version_id', 'resource_id', name='uq_resources_book_version_id_resource_id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_book_version_id'), ['book_version_id'], unique=False)

    op.create_table('scenes',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('start_cp', sa.Integer(), nullable=False),
    sa.Column('end_cp', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PENDING_BOUNDARY', 'CLOSED', name='scene_status', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_scenes_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_book_version_id'), ['book_version_id'], unique=False)

    op.create_table('content_nodes',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.Enum('paragraph', 'heading', 'image', 'ruby', 'rb', 'rt', 'rp', 'footnote', 'separator', 'other', name='content_node_type', native_enum=False), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('tree_json', sa.Text(), nullable=False),
    sa.Column('start_cp', sa.Integer(), nullable=True),
    sa.Column('end_cp', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_content_nodes_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_nodes')),
    sa.UniqueConstraint('chapter_id', 'node_id', name='uq_content_nodes_chapter_id_node_id')
    )
    with op.batch_alter_table('content_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_nodes_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('identity_revisions',
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.Enum('MERGE', 'SPLIT', name='identity_operation', native_enum=False), nullable=False),
    sa.Column('input_ids_json', sa.Text(), nullable=False),
    sa.Column('output_ids_json', sa.Text(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('evidence_refs_json', sa.Text(), nullable=False),
    sa.Column('visible_from_cp', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_identity_revisions_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_revisions'))
    )
    with op.batch_alter_table('identity_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_revisions_scene_id'), ['scene_id'], unique=False)

    op.create_table('inference_runs',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('window_id', sa.String(length=64), nullable=True),
    sa.Column('profile_snapshot_json', sa.Text(), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('remote_request_id', sa.String(length=256), nullable=True),
    sa.Column('state', sa.Enum('PREPARED', 'DISPATCHED', 'SUCCEEDED', 'FAILED', 'UNKNOWN_OUTCOME', name='inference_run_state', native_enum=False), nullable=False),
    sa.Column('usage_json', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_inference_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_runs'))
    )
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_request_fingerprint'), ['request_fingerprint'], unique=False)

    op.create_table('job_windows',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('window_id', sa.String(length=64), nullable=False),
    sa.Column('target_ids_json', sa.Text(), nullable=False),
    sa.Column('dependency_hash', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'PAUSING', 'PAUSED', 'PARTIAL', 'COMPLETED', 'FAILED', 'BUDGET_EXHAUSTED', 'NEEDS_RECONCILIATION', name='job_window_state', native_enum=False), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('lease_until', ndr.storage.types.UtcDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_windows_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_windows')),
    sa.UniqueConstraint('job_id', 'window_id', name='uq_job_windows_job_id_window_id')
    )
    with op.batch_alter_table('job_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_windows_job_id'), ['job_id'], unique=False)

    op.create_table('quotes',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('start_cp', sa.Integer(), nullable=False),
    sa.Column('end_cp', sa.Integer(), nullable=False),
    sa.Column('delimiter', sa.String(length=16), nullable=False),
    sa.Column('nesting_depth', sa.Integer(), nullable=False),
    sa.Column('parent_quote_id', sa.String(length=36), nullable=True),
    sa.Column('utterance_id', sa.String(length=36), nullable=True),
    sa.Column('scanner_version', sa.String(length=64), nullable=False),
    sa.Column('kind_hint', sa.Enum('speech', 'thought', 'quotation', 'group', 'other', 'unknown', name='quote_kind', native_enum=False), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_quotes_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_quotes_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_quote_id'], ['quotes.id'], name=op.f('fk_quotes_parent_quote_id_quotes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('book_version_id', 'start_cp', 'end_cp', 'scanner_version', name='uq_quotes_position')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_book_version_id'), ['book_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_utterance_id'), ['utterance_id'], unique=False)

    op.create_table('gaps',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('left_quote_id', sa.String(length=36), nullable=True),
    sa.Column('right_quote_id', sa.String(length=36), nullable=True),
    sa.Column('start_cp', sa.Integer(), nullable=False),
    sa.Column('end_cp', sa.Integer(), nullable=False),
    sa.Column('proposed_decision', sa.Enum('CONTINUE', 'UPDATE', 'BREAK', 'UNCERTAIN', name='gap_decision', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_gaps_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['left_quote_id'], ['quotes.id'], name=op.f('fk_gaps_left_quote_id_quotes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['right_quote_id'], ['quotes.id'], name=op.f('fk_gaps_right_quote_id_quotes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gaps'))
    )
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gaps_book_version_id'), ['book_version_id'], unique=False)

    op.create_table('scene_memberships',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('valid_from_revision', sa.Integer(), nullable=False),
    sa.Column('valid_to_revision', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_scene_memberships_quote_id_quotes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_memberships_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_memberships'))
    )
    with op.batch_alter_table('scene_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_memberships_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_memberships_scene_id'), ['scene_id'], unique=False)

    op.create_table('speaker_groups',
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('first_quote_id', sa.String(length=36), nullable=True),
    sa.Column('display_label', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_quote_id'], ['quotes.id'], name=op.f('fk_speaker_groups_first_quote_id_quotes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_speaker_groups_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker_groups')),
    sa.UniqueConstraint('scene_id', 'display_label', name='uq_speaker_groups_scene_id_display_label')
    )
    with op.batch_alter_table('speaker_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speaker_groups_scene_id'), ['scene_id'], unique=False)

    op.create_table('annotations',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('speech', 'thought', 'quotation', 'group', 'other', 'unknown', name='annotation_kind', native_enum=False), nullable=False),
    sa.Column('assignment', sa.Enum('EXISTING', 'NEW', 'UNKNOWN', name='annotation_assignment', native_enum=False), nullable=True),
    sa.Column('basis', sa.Enum('DIRECT', 'COREFERENCE', 'RESPONSE_LINK', 'STYLE_ONLY', 'INSUFFICIENT', name='annotation_basis', native_enum=False), nullable=True),
    sa.Column('speaker_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONAL', 'ACCEPTED', 'USER_CONFIRMED', 'UNKNOWN', name='annotation_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('MODEL', 'RULE', 'USER', name='annotation_source', native_enum=False), nullable=False),
    sa.Column('evidence_refs_json', sa.Text(), nullable=False),
    sa.Column('visible_from_cp', sa.Integer(), nullable=True),
    sa.Column('dependency_hash', sa.String(length=64), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('user_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_annotations_quote_id_quotes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_annotations_scene_id_scenes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker_groups.id'], name=op.f('fk_annotations_speaker_id_speaker_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations')),
    sa.UniqueConstraint('quote_id', name='uq_annotations_quote_id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('participants',
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('mention_refs_json', sa.Text(), nullable=False),
    sa.Column('speaker_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_participants_scene_id_scenes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker_groups.id'], name=op.f('fk_participants_speaker_id_speaker_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('annotation_history',
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('visible_from_cp', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('correction_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], name=op.f('fk_annotation_history_annotation_id_annotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation_history')),
    sa.UniqueConstraint('annotation_id', 'revision', name='uq_annotation_history_annotation_id_revision')
    )
    with op.batch_alter_table('annotation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_history_annotation_id'), ['annotation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_history_annotation_id'))

    op.drop_table('annotation_history')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_speaker_id'))
        batch_op.drop_index(batch_op.f('ix_participants_scene_id'))

    op.drop_table('participants')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_speaker_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_scene_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_quote_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('speaker_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speaker_groups_scene_id'))

    op.drop_table('speaker_groups')
    with op.batch_alter_table('scene_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_memberships_scene_id'))
        batch_op.drop_index(batch_op.f('ix_scene_memberships_quote_id'))

    op.drop_table('scene_memberships')
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gaps_book_version_id'))

    op.drop_table('gaps')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_utterance_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_book_version_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('job_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_windows_job_id'))

    op.drop_table('job_windows')
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_runs_request_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_job_id'))

    op.drop_table('inference_runs')
    with op.batch_alter_table('identity_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_revisions_scene_id'))

    op.drop_table('identity_revisions')
    with op.batch_alter_table('content_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_nodes_chapter_id'))

    op.drop_table('content_nodes')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_book_version_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_book_version_id'))

    op.drop_table('resources')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_book_version_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_book_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_book_version_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('book_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_versions_canonical_sha256'))
        batch_op.drop_index(batch_op.f('ix_book_versions_book_id'))

    op.drop_table('book_versions')
    op.drop_table('result_cache')
    op.drop_table('model_profiles')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_books_active_version_id'))

    op.drop_table('books')
    # ### end Alembic commands ###