"""0002 待确认队列与人工更正表

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 01:03:58.234417

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ndr.storage.types  # noqa: F401 - UtcDateTime 列类型需要模块可见


revision: str = "0002"
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrections',
    sa.Column('target_type', sa.Enum('quote', 'gap', 'scene', 'annotation', name='correction_target_type', native_enum=False), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('assign_existing', 'create_speaker', 'set_kind', 'mark_unknown', 'set_gap_decision', 'merge_speakers', 'split_speakers', 'undo', name='correction_action', native_enum=False), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=False),
    sa.Column('after_json', sa.Text(), nullable=False),
    sa.Column('expected_version', sa.Integer(), nullable=True),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('undone_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['undone_by'], ['corrections.id'], name=op.f('fk_corrections_undone_by_corrections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrections_target_type'), ['target_type'], unique=False)

    op.create_table('review_items',
    sa.Column('target_type', sa.Enum('quote', 'gap', name='review_target_type', native_enum=False), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('gap_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Enum('LOW_CONFIDENCE', 'AMBIGUOUS_SPEAKER', 'UNKNOWN_SPEAKER', 'POSSIBLE_NEW_SPEAKER', 'SCENE_BOUNDARY', 'STALE_DEPENDENCY', 'USER_FLAGGED', 'OTHER', name='review_reason', native_enum=False), nullable=False),
    sa.Column('candidates_json', sa.Text(), nullable=False),
    sa.Column('queue_status', sa.Enum('PENDING', 'DEFERRED', 'RESOLVED', name='review_queue_status', native_enum=False), nullable=False),
    sa.Column('annotation_version', sa.Integer(), nullable=True),
    sa.Column('resolved_by_correction_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('(quote_id IS NULL) <> (gap_id IS NULL)', name=op.f('ck_review_items_exactly_one_target')),
    sa.ForeignKeyConstraint(['gap_id'], ['gaps.id'], name=op.f('fk_review_items_gap_id_gaps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_review_items_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items')),
    sa.UniqueConstraint('gap_id', 'reason', name='uq_review_items_gap_id_reason'),
    sa.UniqueConstraint('quote_id', 'reason', name='uq_review_items_quote_id_reason')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_gap_id'), ['gap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_queue_status'), ['queue_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_quote_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_queue_status'))
        batch_op.drop_index(batch_op.f('ix_review_items_gap_id'))

    op.drop_table('review_items')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_target_type'))
        batch_op.drop_index(batch_op.f('ix_corrections_target_id'))

    op.drop_table('corrections')
    # ### end Alembic commands ###