"""0003 canonical 全文路径与 source_map 映射表

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 01:13:15.730868

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ndr.storage.types  # noqa: F401 - UtcDateTime 列类型需要模块可见


revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_mappings',
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('canonical_start_cp', sa.Integer(), nullable=False),
    sa.Column('canonical_end_cp', sa.Integer(), nullable=False),
    sa.Column('source_href', sa.String(length=1024), nullable=True),
    sa.Column('source_text_start_cp', sa.Integer(), nullable=False),
    sa.Column('source_text_end_cp', sa.Integer(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_text_mappings_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_text_mappings_chapter_id_chapters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_mappings'))
    )
    with op.batch_alter_table('text_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_mappings_book_version_id'), ['book_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_mappings_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index('ix_text_mappings_version_canonical', ['book_version_id', 'canonical_start_cp'], unique=False)
        batch_op.create_index('ix_text_mappings_version_ordinal', ['book_version_id', 'ordinal'], unique=False)
        batch_op.create_index('ix_text_mappings_version_source', ['book_version_id', 'source_text_start_cp'], unique=False)

    with op.batch_alter_table('book_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_versions', schema=None) as batch_op:
        batch_op.drop_column('canonical_path')

    with op.batch_alter_table('text_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_text_mappings_version_source')
        batch_op.drop_index('ix_text_mappings_version_ordinal')
        batch_op.drop_index('ix_text_mappings_version_canonical')
        batch_op.drop_index(batch_op.f('ix_text_mappings_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_text_mappings_book_version_id'))

    op.drop_table('text_mappings')
    # ### end Alembic commands ###