"""0004 阅读进度：书签版本与阅读模式

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 01:31:33.481431

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_position_version_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('reading_mode', sa.Enum('initial', 'reread', name='reading_mode', native_enum=False), server_default='initial', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('reading_mode')
        batch_op.drop_column('read_position_version_id')

    # ### end Alembic commands ###