"""0005 导出快照与产物

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 04:44:17.897132

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ndr.storage.types  # noqa: F401 - UtcDateTime 列类型需要模块可见


revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_snapshots',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('book_version_id', sa.String(length=36), nullable=False),
    sa.Column('selected_chapter_ids_json', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.String(length=64), nullable=False),
    sa.Column('annotation_projection_json', sa.Text(), nullable=False),
    sa.Column('identity_projection_json', sa.Text(), nullable=False),
    sa.Column('visibility_policy', sa.String(length=32), nullable=False),
    sa.Column('style_json', sa.Text(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_export_snapshots_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_version_id'], ['book_versions.id'], name=op.f('fk_export_snapshots_book_version_id_book_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_snapshots'))
    )
    with op.batch_alter_table('export_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_snapshots_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_snapshots_book_version_id'), ['book_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_snapshots_snapshot_hash'), ['snapshot_hash'], unique=False)

    op.create_table('export_artifacts',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.Enum('epub', 'html', name='export_format', native_enum=False), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('exporter_version', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('validation_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ndr.storage.types.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_export_artifacts_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['export_snapshots.id'], name=op.f('fk_export_artifacts_snapshot_id_export_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_artifacts'))
    )
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_artifacts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_artifacts_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_fingerprint'))

    op.drop_table('export_artifacts')
    with op.batch_alter_table('export_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_snapshots_snapshot_hash'))
        batch_op.drop_index(batch_op.f('ix_export_snapshots_book_version_id'))
        batch_op.drop_index(batch_op.f('ix_export_snapshots_book_id'))

    op.drop_table('export_snapshots')
    # ### end Alembic commands ###
